### PR TITLE
BattleMeshV9, Porto, Portugal

### PR DESCRIPTION
**Pull request by yangwao**
right after squatconf

### CODE REVIEW

**Comment by yangwao** [comment]
Paralel Polis Congress in Prague!

**Comment by watson** [comment]
@yangwao Thanks :smiley: Really wanna go to BattleMesh! Sorry I didn't see this PR before now, so I ended up making some commits that introduced merge conflicts. Could I get you to rebase it against master?

**Comment by yangwao** [comment]
this could work now? :) I did my best :dancers:

**Comment by watson** [comment]
@yangwao awesome, thanks :)

**Pull request merged**
