### PR TITLE
Added EMFCamp and BalCCon

### PR DESCRIPTION
**Pull request by yangwao**
You really need go to BalCCon, this is really hilarious badge https://www.youtube.com/watch?v=IFifeMkfip8 :rocket: 
badge with password generator xD

### CODE REVIEW

**Comment by yangwao** [comment]
and also acts as tv-b-gone :)

**Comment by watson** [comment]
@yangwao thanks :smile:

**Comment by yangwao** [comment]
What you say about that BalCCon badge? Hilarious huh :)

**Comment by watson** [comment]
@yangwao yeah, reminds me of the CCC and DEFCON badges :smiley:

**Pull request merged**
