### PR TITLE
Added jsMobileConf 2018

### PR DESCRIPTION
**Pull request by skarthikeyan96**

### CODE REVIEW

**Comment by watson** [comment]
Thanks for adding this conference 😃 

Could I get you to remove the 2nd `Oct` from the date column?

**Comment by skarthikeyan96** [comment]
I am not able to see an entry for 2nd October. Which one are you saying?

**Comment by watson** [comment]
You just wrote `Oct` twice 😃 

```diff
-[jsMobileConf](https://jsmobileconf.com/) | Oct 25th - Oct26th | Unknown | Boston, USA |
+[jsMobileConf](https://jsmobileconf.com/) | Oct 25th - 26th | Unknown | Boston, USA |
```

**Comment by skarthikeyan96** [comment]
Oh okay, will do that right away

**Comment by skarthikeyan96** [comment]
Done @watson

**Comment by watson** [comment]
Awesome, thanks for helping make this a great list 😃

**Pull request merged**
