### PR TITLE
pixels.camp

### PR DESCRIPTION
**Pull request by daviddias**
pixels.camp is codebits reborn! :D (codebits was http://codebits.eu/)

small review of the last edition: https://videos.sapo.pt/IyusNAZ791ZdoCY5H5IF

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Cool. @diasdavid I guess you are going? :)

**Comment by daviddias** [comment]
Yes :D

**Comment by watson** [comment]
Cool!

**Comment by watson** [comment]
@diasdavid thanks :)

**Pull request merged**
